name: Etebase Docker Image
on:
  push:
  schedule:
    - cron: '0 22 * * Fri'
jobs:
  pull-latest-code:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: build

      - uses: actions/checkout@v2
        with:
          repository: etesync/server
          fetch-depth: 0
          ref: master
          path: etebase
        
      - name: Set latest tag
        working-directory: ./etebase
        run: echo "LATEST_TAG=$(git describe --tags)" >> $GITHUB_ENV

      - name: Print tag
        working-directory: ./etebase
        run: echo ${{ env.LATEST_TAG }}

      - name: Checkout latest tag
        working-directory: ./etebase
        run: git checkout tags/${{ env.LATEST_TAG }}

      - name: Copy from Build dir
        working-directory: ./etebase
        run: cp ../build/* ./

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into Dockerhub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./etebase
          file: ./build/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/etebase:${{ env.LATEST_TAG }}
